/* Generado por tools/build_manifest.py - no editar a mano */
window.BB = window.BB || {};
BB.SPRITES = {
  "enemy_goblin_veloz": {"src": "sprites/enemies/goblin_veloz.webp", "w": 384, "h": 368, "facing": "right"},
  "enemy_orco_escudo": {"src": "sprites/enemies/orco_escudo.webp", "w": 366, "h": 384, "facing": "right"},
  "enemy_goblin_bombardero": {"src": "sprites/enemies/goblin_bombardero.webp", "w": 378, "h": 384, "facing": "right"},
  "enemy_goblin_planeador": {"src": "sprites/enemies/goblin_planeador.webp", "w": 383, "h": 384, "facing": "right"},
  "enemy_jinete_lobo": {"src": "sprites/enemies/jinete_lobo.webp", "w": 384, "h": 253, "facing": "right"},
  "enemy_chaman": {"src": "sprites/enemies/chaman.webp", "w": 327, "h": 384, "facing": "right"},
  "enemy_goblin_arquero": {"src": "sprites/enemies/goblin_arquero.webp", "w": 377, "h": 384, "facing": "right"},
  "enemy_orco_berserker": {"src": "sprites/enemies/orco_berserker.webp", "w": 363, "h": 384, "facing": "right"},
  "enemy_orco_tambor": {"src": "sprites/enemies/orco_tambor.webp", "w": 377, "h": 384, "facing": "right"},
  "enemy_goblin_topo": {"src": "sprites/enemies/goblin_topo.webp", "w": 352, "h": 384, "facing": "right"},
  "enemy_troll": {"src": "sprites/enemies/troll.webp", "w": 384, "h": 376, "facing": "right"},
  "enemy_orco_ariete": {"src": "sprites/enemies/orco_ariete.webp", "w": 384, "h": 231, "facing": "right"},
  "hero_arquera": {"src": "sprites/heroes/arquera.webp", "w": 298, "h": 384, "facing": "left"},
  "hero_mago_fuego": {"src": "sprites/heroes/mago_fuego.webp", "w": 323, "h": 384, "facing": "left"},
  "hero_maga_hielo": {"src": "sprites/heroes/maga_hielo.webp", "w": 290, "h": 384, "facing": "left"},
  "hero_ballestero": {"src": "sprites/heroes/ballestero.webp", "w": 384, "h": 375, "facing": "left"},
  "hero_sacerdote": {"src": "sprites/heroes/sacerdote.webp", "w": 314, "h": 384, "facing": "left"},
  "hero_ingeniero": {"src": "sprites/heroes/ingeniero.webp", "w": 377, "h": 384, "facing": "left"},
  "hero_hechicera_rayo": {"src": "sprites/heroes/hechicera_rayo.webp", "w": 369, "h": 384, "facing": "left"},
  "hero_druida": {"src": "sprites/heroes/druida.webp", "w": 348, "h": 384, "facing": "left"},
  "hero_alquimista": {"src": "sprites/heroes/alquimista.webp", "w": 354, "h": 384, "facing": "left"},
  "hero_martillo": {"src": "sprites/heroes/martillo.webp", "w": 372, "h": 384, "facing": "left"},
  "hero_bardo": {"src": "sprites/heroes/bardo.webp", "w": 366, "h": 384, "facing": "left"},
  "hero_brujo": {"src": "sprites/heroes/brujo.webp", "w": 350, "h": 384, "facing": "left"},
  "hero_halconera": {"src": "sprites/heroes/halconera.webp", "w": 384, "h": 384, "facing": "left"},
  "hero_arcano": {"src": "sprites/heroes/arcano.webp", "w": 337, "h": 384, "facing": "left"},
  "hero_granadero": {"src": "sprites/heroes/granadero.webp", "w": 374, "h": 384, "facing": "left"},
  "hero_cazadora": {"src": "sprites/heroes/cazadora.webp", "w": 369, "h": 384, "facing": "left"},
  "hero_monje_viento": {"src": "sprites/heroes/monje_viento.webp", "w": 324, "h": 384, "facing": "left"},
  "hero_envenenadora": {"src": "sprites/heroes/envenenadora.webp", "w": 284, "h": 384, "facing": "left"},
  "hero_sacerdotisa_sol": {"src": "sprites/heroes/sacerdotisa_sol.webp", "w": 346, "h": 384, "facing": "left"},
  "hero_mosquetera": {"src": "sprites/heroes/mosquetera.webp", "w": 352, "h": 384, "facing": "left"},
  "boss_rey_goblin": {"src": "sprites/bosses/rey_goblin.webp", "w": 574, "h": 640, "facing": "right"},
  "boss_chaman_gigante": {"src": "sprites/bosses/chaman_gigante.webp", "w": 603, "h": 640, "facing": "right"},
  "boss_troll_piedra": {"src": "sprites/bosses/troll_piedra.webp", "w": 640, "h": 639, "facing": "right"},
  "boss_escorpion": {"src": "sprites/bosses/escorpion.webp", "w": 640, "h": 418, "facing": "right"},
  "boss_senor_fuego": {"src": "sprites/bosses/senor_fuego.webp", "w": 609, "h": 640, "facing": "right"},
  "boss_senor_guerra": {"src": "sprites/bosses/senor_guerra.webp", "w": 581, "h": 640, "facing": "right"},
  "boss_gigante_escarcha": {"src": "sprites/bosses/gigante_escarcha.webp", "w": 639, "h": 640, "facing": "right"},
  "boss_nigromante": {"src": "sprites/bosses/nigromante.webp", "w": 622, "h": 640, "facing": "right"},
  "boss_golem": {"src": "sprites/bosses/golem.webp", "w": 640, "h": 635, "facing": "right"},
  "boss_dragon": {"src": "sprites/bosses/dragon.webp", "w": 640, "h": 431, "facing": "right"},
  "castle_1": {"src": "sprites/castle/castle_1.webp", "w": 690, "h": 768, "facing": "left"},
  "castle_2": {"src": "sprites/castle/castle_2.webp", "w": 768, "h": 766, "facing": "left"},
  "castle_3": {"src": "sprites/castle/castle_3.webp", "w": 725, "h": 768, "facing": "left"},
  "castle_4": {"src": "sprites/castle/castle_4.webp", "w": 768, "h": 761, "facing": "left"},
  "castle_5": {"src": "sprites/castle/castle_5.webp", "w": 742, "h": 768, "facing": "left"},
  "tower_pinchos": {"src": "sprites/towers/pinchos.webp", "w": 384, "h": 204},
  "tower_catapulta": {"src": "sprites/towers/catapulta.webp", "w": 384, "h": 285, "facing": "left"},
  "tower_rayos": {"src": "sprites/towers/rayos.webp", "w": 142, "h": 384},
  "tower_flechas": {"src": "sprites/towers/flechas.webp", "w": 253, "h": 384, "facing": "left"},
  "tower_brea": {"src": "sprites/towers/brea.webp", "w": 384, "h": 264},
  "tower_barricada": {"src": "sprites/towers/barricada.webp", "w": 384, "h": 213, "facing": "left"},
  "bg_bosque": {"src": "sprites/bg/bosque.webp", "w": 1600, "h": 720},
  "bg_pantano": {"src": "sprites/bg/pantano.webp", "w": 1600, "h": 720},
  "bg_montanas": {"src": "sprites/bg/montanas.webp", "w": 1600, "h": 720},
  "bg_desierto": {"src": "sprites/bg/desierto.webp", "w": 1600, "h": 720},
  "bg_volcan": {"src": "sprites/bg/volcan.webp", "w": 1600, "h": 720},
  "bg_oscuras": {"src": "sprites/bg/oscuras.webp", "w": 1600, "h": 720},
  "bg_hielo": {"src": "sprites/bg/hielo.webp", "w": 1600, "h": 720},
  "bg_ruinas": {"src": "sprites/bg/ruinas.webp", "w": 1600, "h": 720},
  "bg_forja": {"src": "sprites/bg/forja.webp", "w": 1600, "h": 720},
  "bg_dragon": {"src": "sprites/bg/dragon.webp", "w": 1600, "h": 720},
  "map_bosque": {"src": "sprites/map/bosque.webp", "w": 1280, "h": 720},
  "map_pantano": {"src": "sprites/map/pantano.webp", "w": 1280, "h": 720},
  "map_montanas": {"src": "sprites/map/montanas.webp", "w": 1280, "h": 720},
  "map_desierto": {"src": "sprites/map/desierto.webp", "w": 1280, "h": 720},
  "map_volcan": {"src": "sprites/map/volcan.webp", "w": 1280, "h": 720},
  "map_oscuras": {"src": "sprites/map/oscuras.webp", "w": 1280, "h": 720},
  "map_hielo": {"src": "sprites/map/hielo.webp", "w": 1280, "h": 720},
  "map_ruinas": {"src": "sprites/map/ruinas.webp", "w": 1280, "h": 720},
  "map_forja": {"src": "sprites/map/forja.webp", "w": 1280, "h": 720},
  "map_dragon": {"src": "sprites/map/dragon.webp", "w": 1280, "h": 720},
  "icon_gold": {"src": "sprites/icons/gold.webp", "w": 244, "h": 256},
  "icon_gem": {"src": "sprites/icons/gem.webp", "w": 256, "h": 241},
  "icon_star": {"src": "sprites/icons/star.webp", "w": 232, "h": 256},
  "icon_lock": {"src": "sprites/icons/lock.webp", "w": 197, "h": 256},
  "icon_heart": {"src": "sprites/icons/heart.webp", "w": 256, "h": 250},
  "icon_sword": {"src": "sprites/icons/sword.webp", "w": 251, "h": 256},
  "icon_shield": {"src": "sprites/icons/shield.webp", "w": 193, "h": 256},
  "icon_castle": {"src": "sprites/icons/castle.webp", "w": 226, "h": 256},
  "icon_trophy": {"src": "sprites/icons/trophy.webp", "w": 209, "h": 256},
  "icon_gift": {"src": "sprites/icons/gift.webp", "w": 251, "h": 256},
  "icon_scroll": {"src": "sprites/icons/scroll.webp", "w": 256, "h": 254},
  "icon_skull": {"src": "sprites/icons/skull.webp", "w": 241, "h": 256},
  "icon_lightning": {"src": "sprites/icons/lightning.webp", "w": 186, "h": 256},
  "icon_fire": {"src": "sprites/icons/fire.webp", "w": 142, "h": 256},
  "icon_snow": {"src": "sprites/icons/snow.webp", "w": 253, "h": 256},
  "icon_potion": {"src": "sprites/icons/potion.webp", "w": 256, "h": 248},
  "icon_hammer": {"src": "sprites/icons/hammer.webp", "w": 256, "h": 251},
  "icon_map": {"src": "sprites/icons/map.webp", "w": 256, "h": 249},
  "icon_settings": {"src": "sprites/icons/settings.webp", "w": 256, "h": 250},
  "icon_play": {"src": "sprites/icons/play.webp", "w": 256, "h": 215},
  "title_art": {"src": "sprites/ui/title_art.webp", "w": 1600, "h": 900},
  "app_icon": {"src": "sprites/icons/app_icon_512.png", "w": 512, "h": 512, "src192": "sprites/icons/app_icon_192.png"}
};
