/* Generado por tools/build_manifest.py - no editar a mano */
window.BB = window.BB || {};
BB.SPRITES = {
  "enemy_goblin_veloz": {"src": "sprites/enemies/goblin_veloz.webp", "w": 384, "h": 363, "facing": "right"},
  "enemy_orco_escudo": {"src": "sprites/enemies/orco_escudo.webp", "w": 350, "h": 384, "facing": "right"},
  "enemy_goblin_bombardero": {"src": "sprites/enemies/goblin_bombardero.webp", "w": 384, "h": 381, "facing": "right"},
  "enemy_goblin_planeador": {"src": "sprites/enemies/goblin_planeador.webp", "w": 384, "h": 382, "facing": "right"},
  "enemy_jinete_lobo": {"src": "sprites/enemies/jinete_lobo.webp", "w": 384, "h": 253, "facing": "right"},
  "enemy_chaman": {"src": "sprites/enemies/chaman.webp", "w": 328, "h": 384, "facing": "right"},
  "enemy_goblin_arquero": {"src": "sprites/enemies/goblin_arquero.webp", "w": 384, "h": 364, "facing": "right"},
  "enemy_orco_berserker": {"src": "sprites/enemies/orco_berserker.webp", "w": 384, "h": 380, "facing": "right"},
  "enemy_orco_tambor": {"src": "sprites/enemies/orco_tambor.webp", "w": 365, "h": 384, "facing": "right"},
  "enemy_goblin_topo": {"src": "sprites/enemies/goblin_topo.webp", "w": 384, "h": 356, "facing": "right"},
  "enemy_troll": {"src": "sprites/enemies/troll.webp", "w": 382, "h": 384, "facing": "right"},
  "enemy_orco_ariete": {"src": "sprites/enemies/orco_ariete.webp", "w": 384, "h": 249, "facing": "right"},
  "hero_arquera": {"src": "sprites/heroes/arquera.webp", "w": 384, "h": 370, "facing": "left"},
  "hero_mago_fuego": {"src": "sprites/heroes/mago_fuego.webp", "w": 305, "h": 384, "facing": "left"},
  "hero_maga_hielo": {"src": "sprites/heroes/maga_hielo.webp", "w": 290, "h": 384, "facing": "left"},
  "hero_ballestero": {"src": "sprites/heroes/ballestero.webp", "w": 330, "h": 384, "facing": "left"},
  "hero_sacerdote": {"src": "sprites/heroes/sacerdote.webp", "w": 326, "h": 384, "facing": "left"},
  "hero_ingeniero": {"src": "sprites/heroes/ingeniero.webp", "w": 230, "h": 384, "facing": "left"},
  "hero_hechicera_rayo": {"src": "sprites/heroes/hechicera_rayo.webp", "w": 354, "h": 384, "facing": "left"},
  "hero_druida": {"src": "sprites/heroes/druida.webp", "w": 263, "h": 384, "facing": "left"},
  "hero_alquimista": {"src": "sprites/heroes/alquimista.webp", "w": 302, "h": 384, "facing": "left"},
  "hero_martillo": {"src": "sprites/heroes/martillo.webp", "w": 312, "h": 384, "facing": "left"},
  "hero_bardo": {"src": "sprites/heroes/bardo.webp", "w": 340, "h": 384, "facing": "left"},
  "hero_brujo": {"src": "sprites/heroes/brujo.webp", "w": 363, "h": 384, "facing": "left"},
  "hero_halconera": {"src": "sprites/heroes/halconera.webp", "w": 375, "h": 384, "facing": "left"},
  "hero_arcano": {"src": "sprites/heroes/arcano.webp", "w": 367, "h": 384, "facing": "left"},
  "hero_granadero": {"src": "sprites/heroes/granadero.webp", "w": 351, "h": 384, "facing": "left"},
  "hero_cazadora": {"src": "sprites/heroes/cazadora.webp", "w": 384, "h": 342, "facing": "left"},
  "hero_monje_viento": {"src": "sprites/heroes/monje_viento.webp", "w": 341, "h": 384, "facing": "left"},
  "hero_envenenadora": {"src": "sprites/heroes/envenenadora.webp", "w": 366, "h": 384, "facing": "left"},
  "hero_sacerdotisa_sol": {"src": "sprites/heroes/sacerdotisa_sol.webp", "w": 347, "h": 384, "facing": "left"},
  "hero_mosquetera": {"src": "sprites/heroes/mosquetera.webp", "w": 302, "h": 384, "facing": "left"},
  "troop_arquero": {"src": "sprites/troops/arquero.webp", "w": 265, "h": 320, "facing": "left"},
  "troop_ballestero": {"src": "sprites/troops/ballestero.webp", "w": 305, "h": 320, "facing": "left"},
  "troop_aprendiz": {"src": "sprites/troops/aprendiz.webp", "w": 255, "h": 320, "facing": "left"},
  "troop_lanzapiedras": {"src": "sprites/troops/lanzapiedras.webp", "w": 188, "h": 320, "facing": "left"},
  "deco_empalizada": {"src": "sprites/deco/empalizada.webp", "w": 512, "h": 292},
  "deco_tienda": {"src": "sprites/deco/tienda.webp", "w": 512, "h": 511},
  "deco_atalaya": {"src": "sprites/deco/atalaya.webp", "w": 360, "h": 512},
  "deco_barriles": {"src": "sprites/deco/barriles.webp", "w": 504, "h": 512},
  "deco_estandarte": {"src": "sprites/deco/estandarte.webp", "w": 225, "h": 512},
  "deco_hoguera": {"src": "sprites/deco/hoguera.webp", "w": 512, "h": 501},
  "deco_carro": {"src": "sprites/deco/carro.webp", "w": 512, "h": 377},
  "deco_arbol": {"src": "sprites/deco/arbol.webp", "w": 411, "h": 512},
  "deco_arbusto": {"src": "sprites/deco/arbusto.webp", "w": 499, "h": 512},
  "deco_roca": {"src": "sprites/deco/roca.webp", "w": 463, "h": 512},
  "boss_rey_goblin": {"src": "sprites/bosses/rey_goblin.webp", "w": 533, "h": 640, "facing": "right"},
  "boss_chaman_gigante": {"src": "sprites/bosses/chaman_gigante.webp", "w": 621, "h": 640, "facing": "right"},
  "boss_troll_piedra": {"src": "sprites/bosses/troll_piedra.webp", "w": 580, "h": 640, "facing": "right"},
  "boss_escorpion": {"src": "sprites/bosses/escorpion.webp", "w": 640, "h": 448, "facing": "right"},
  "boss_senor_fuego": {"src": "sprites/bosses/senor_fuego.webp", "w": 640, "h": 611, "facing": "right"},
  "boss_senor_guerra": {"src": "sprites/bosses/senor_guerra.webp", "w": 640, "h": 600, "facing": "right"},
  "boss_gigante_escarcha": {"src": "sprites/bosses/gigante_escarcha.webp", "w": 603, "h": 640, "facing": "right"},
  "boss_nigromante": {"src": "sprites/bosses/nigromante.webp", "w": 633, "h": 640, "facing": "right"},
  "boss_golem": {"src": "sprites/bosses/golem.webp", "w": 640, "h": 639, "facing": "right"},
  "boss_dragon": {"src": "sprites/bosses/dragon.webp", "w": 640, "h": 431, "facing": "right"},
  "castle_1": {"src": "sprites/castle/castle_1.webp", "w": 412, "h": 768, "facing": "left"},
  "castle_2": {"src": "sprites/castle/castle_2.webp", "w": 678, "h": 768, "facing": "left"},
  "castle_3": {"src": "sprites/castle/castle_3.webp", "w": 671, "h": 768, "facing": "left"},
  "castle_4": {"src": "sprites/castle/castle_4.webp", "w": 763, "h": 768, "facing": "left"},
  "castle_5": {"src": "sprites/castle/castle_5.webp", "w": 768, "h": 757, "facing": "left"},
  "tower_pinchos": {"src": "sprites/towers/pinchos.webp", "w": 384, "h": 264},
  "tower_catapulta": {"src": "sprites/towers/catapulta.webp", "w": 384, "h": 338, "facing": "left"},
  "tower_rayos": {"src": "sprites/towers/rayos.webp", "w": 218, "h": 384},
  "tower_flechas": {"src": "sprites/towers/flechas.webp", "w": 261, "h": 384, "facing": "left"},
  "tower_brea": {"src": "sprites/towers/brea.webp", "w": 384, "h": 262},
  "tower_barricada": {"src": "sprites/towers/barricada.webp", "w": 384, "h": 223, "facing": "left"},
  "bg_bosque": {"src": "sprites/bg/bosque.webp", "w": 1600, "h": 720},
  "bg_pantano": {"src": "sprites/bg/pantano.webp", "w": 1600, "h": 720},
  "bg_montanas": {"src": "sprites/bg/montanas.webp", "w": 1600, "h": 720},
  "bg_desierto": {"src": "sprites/bg/desierto.webp", "w": 1600, "h": 720},
  "bg_volcan": {"src": "sprites/bg/volcan.webp", "w": 1600, "h": 720},
  "bg_oscuras": {"src": "sprites/bg/oscuras.webp", "w": 1600, "h": 720},
  "bg_hielo": {"src": "sprites/bg/hielo.webp", "w": 1600, "h": 720},
  "bg_ruinas": {"src": "sprites/bg/ruinas.webp", "w": 1600, "h": 720},
  "bg_forja": {"src": "sprites/bg/forja.webp", "w": 1600, "h": 720},
  "bg_dragon": {"src": "sprites/bg/dragon.webp", "w": 1600, "h": 720},
  "map_bosque": {"src": "sprites/map/bosque.webp", "w": 1280, "h": 720},
  "map_pantano": {"src": "sprites/map/pantano.webp", "w": 1280, "h": 720},
  "map_montanas": {"src": "sprites/map/montanas.webp", "w": 1280, "h": 720},
  "map_desierto": {"src": "sprites/map/desierto.webp", "w": 1280, "h": 720},
  "map_volcan": {"src": "sprites/map/volcan.webp", "w": 1280, "h": 720},
  "map_oscuras": {"src": "sprites/map/oscuras.webp", "w": 1280, "h": 720},
  "map_hielo": {"src": "sprites/map/hielo.webp", "w": 1280, "h": 720},
  "map_ruinas": {"src": "sprites/map/ruinas.webp", "w": 1280, "h": 720},
  "map_forja": {"src": "sprites/map/forja.webp", "w": 1280, "h": 720},
  "map_dragon": {"src": "sprites/map/dragon.webp", "w": 1280, "h": 720},
  "icon_gold": {"src": "sprites/icons/gold.webp", "w": 255, "h": 256},
  "icon_gem": {"src": "sprites/icons/gem.webp", "w": 256, "h": 250},
  "icon_star": {"src": "sprites/icons/star.webp", "w": 242, "h": 256},
  "icon_lock": {"src": "sprites/icons/lock.webp", "w": 197, "h": 256},
  "icon_heart": {"src": "sprites/icons/heart.webp", "w": 256, "h": 253},
  "icon_sword": {"src": "sprites/icons/sword.webp", "w": 77, "h": 256},
  "icon_shield": {"src": "sprites/icons/shield.webp", "w": 230, "h": 256},
  "icon_castle": {"src": "sprites/icons/castle.webp", "w": 244, "h": 256},
  "icon_trophy": {"src": "sprites/icons/trophy.webp", "w": 230, "h": 256},
  "icon_gift": {"src": "sprites/icons/gift.webp", "w": 248, "h": 256},
  "icon_scroll": {"src": "sprites/icons/scroll.webp", "w": 256, "h": 167},
  "icon_skull": {"src": "sprites/icons/skull.webp", "w": 242, "h": 256},
  "icon_lightning": {"src": "sprites/icons/lightning.webp", "w": 125, "h": 256},
  "icon_fire": {"src": "sprites/icons/fire.webp", "w": 199, "h": 256},
  "icon_snow": {"src": "sprites/icons/snow.webp", "w": 255, "h": 256},
  "icon_potion": {"src": "sprites/icons/potion.webp", "w": 145, "h": 256},
  "icon_hammer": {"src": "sprites/icons/hammer.webp", "w": 244, "h": 256},
  "icon_map": {"src": "sprites/icons/map.webp", "w": 256, "h": 255},
  "icon_settings": {"src": "sprites/icons/settings.webp", "w": 256, "h": 252},
  "icon_play": {"src": "sprites/icons/play.webp", "w": 256, "h": 244},
  "title_art": {"src": "sprites/ui/title_art.webp", "w": 1600, "h": 900},
  "app_icon": {"src": "sprites/icons/app_icon_512.png", "w": 512, "h": 512, "src192": "sprites/icons/app_icon_192.png"}
};
